#!/bin/sh

if [ $# -eq 0 ]; then
    remotes=$(git remote)
else
    remotes=$@
fi

date | tee timestamp && git commit -am"Update: $(cat timestamp)" && parallel -j4 time git push --force {} ::: ${remotes}
